apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviewservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reviewservice
  template:
    metadata:
      labels:
        app: reviewservice
    spec:
      containers:
      - name: reviewservice
        image: reviewservice-main-review-service
        imagePullPolicy: Never
        ports:
        - containerPort: 3003
---
apiVersion: v1
kind: Service
metadata:
  name: reviewservice-service
spec:
  type: NodePort
  selector:
    app: reviewservice
  ports:
  - port: 80
    targetPort: 3003
    nodePort: 30009